### ISSUE TITLE
Missing message when test fails. 

### ISSUE THREAD

**Issue by szwendacz** [avidit/newman-reporter-slack#11]
Hi Guys, 

You made a great tool but I have one, small problem. When my Postman suite is all green tests result is published on the specific channel on the Slack. Unfortunately, when one or more tests failed the result of the test isn't published. I don't know why and I have no idea how to check it. Thanks for any ideas.

**Comment by rmkranack** [comment]
I am having the same issue.

**Comment by shreys7** [comment]
This is because for a failed test, if `-x` option is not passed to newman, it immediately exits the process. You can run newman using `-x` and then this should work as expected. 
https://community.postman.com/t/asynchronous-upload-of-report-inside-a-newman-reporter/4737/3
