### ISSUE TITLE
Report doesn't send over Slack

### ISSUE THREAD

**Issue by baonguyen1108** [avidit/newman-reporter-slack#2]
Hi,

I have set up everything per instruction. Upon the newman run, there's no error throw but report won't send over Slack.

Can you help me figure it out? 

Thanks

**Comment by robinbobbitt** [comment]
@baonguyen1108 I'm guessing you're using newman CLI. The process exits before the asynchronous slack request has a chance to complete. I was able to avoid this using the `--suppress-exit-code` CLI option. Your other option is to invoke newman programmatically rather than use the CLI.

**Comment by OTATA** [comment]
Hi, in my case, an error occurs
`An HTTP protocol error occurred: statusCode = undefined`

The problems is the Channel:

```
let msg = {
                channel: channel,
                text: text
}

```
I took it and worked, cause when you config an Incoming WebHooks you do not need pass the channel

**Comment by avidit** [comment]
@OTATA Thank you very much. I have merged your changes.
