### ISSUE TITLE
Slack report is not being posted 

### ISSUE THREAD

**Issue by badarilr** [avidit/newman-reporter-slack#5]
The command runs successfully , unfortunately not being posted to slack.

Command Used :

newman run "C:\Users\XXXXr\Desktop\Mobile API List.postman_collection.json" -e C:\Users\XXXX\Desktop\QA.postman_environment.json -r cli,slack --reporter-slack-channel '#api' --reporter-slack-webhook-url "

**Comment by avidit** [comment]
@badarilr Please don't use your actual webhook url while posting comments in public forum.
Was there any error in console?

**Comment by badarilr** [comment]
Nope there was no error in the console .

newman run "Mobile.postman_collection.json" -e "QA.postman_environment.json" -r cli,slack --reporter-slack-channel '#api' --reporter-slack-webhook-url 'https://hooks.slack.com/services/XXX/XXX'

Hope the command is correct ?

**Comment by badarilr** [comment]
well the webhook url is correct (i double checked with curl), did i messed with any other parameters??

**Comment by avidit** [comment]
Everything looks ok. Do you see summary in the terminal?

**Comment by badarilr** [comment]
Yep summary is bring posted.
