### ISSUE TITLE
Adding Failures

### ISSUE THREAD

**Issue by donmax** [avidit/newman-reporter-slack#6]
Hi!
It's not an issue but the idea to improvement.
I liked the compact output of the package. The single thing that I need and maybe important tot others - add detailed info about all Failures like newman CLI reporter does it. The detailing failures feature maybe  a flag in the options in the case somebody no needs it.
Thanks!

**Comment by ckenst** [comment]
I think this would at least be partially solved by PR #7

**Comment by avidit** [comment]
I hope PR #7 will address this
