### ISSUE TITLE
Not posted

### ISSUE THREAD

**Issue by PavelTeslenko** [avidit/newman-reporter-slack#8]
Hello,
As per instruction, I run
newman run (jsonname).json -r cli,slack --reporter-slack-channel '#deploy' --reporter-slack-webhook-url 'https://hooks.slack.com/(further url)' 

the json itself is executed without any errors, yet no output is posted on slack.
is that a known issue of some kind?

**Comment by mshivanna** [comment]
this has a bug. it only sends notification when all the tests are passed. It fails to send notification when one of the tests have failed. It defeats the purpose of using this reporter :(

**Comment by mprakasham-clgx** [comment]
Please use "--suppress-exit-code" newman parameter, it should help notify with failed tests as well.
