### ISSUE TITLE
Not getting notifications for failed test

### ISSUE THREAD

**Issue by kapilaNR** [avidit/newman-reporter-slack#9]
I got the notifications only when all the tests are passed.
If one of test failing it will not getting notify.

**Comment by mshivanna** [comment]
Same issue. I can see notification when all the tests are passed.

**Comment by mprakasham-clgx** [comment]
Please use "--suppress-exit-code" newman parameter, it should help notify with failed tests as well.

**Comment by david2003542** [comment]
@mprakasham  it works. Can I ask one question here is that available to have red colour show on slack during the failed tests happened?

**Comment by ajunior** [comment]
I wonder if is it possible to notify only failed tests?

**Comment by yogs0616** [comment]
@mprakasham does this has ability to show all failed tests and its short details?
